# Generated by Django 3.0.7 on 2020-06-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanphammodel',
            name='Anh',
            field=models.ImageField(upload_to='images'),
        ),
    ]
